language: go # or any other language

env:
  global:
    - COSIGN_KEY="cosign.key"

before_install:
  - echo "$SSH_KEY_FOR_SIGNING" | base64 --decode > $COSIGN_KEY
  - chmod 600 $COSIGN_KEY

script:
  - echo "Build and test commands would go here if there were any"
  - echo "Signing the dummy artifact"
  - cosign sign-blob --key $COSIGN_KEY artifact.txt
